name: Deploy Static Website to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Ambil kode dari GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Deploy ke EC2 via SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          port: 22
          script: |
            echo "=== CLEAN OLD FILES ==="
            sudo rm -rf /var/www/html/*

            echo "=== COPY NEW FILES ==="
            sudo cp -r /home/ubuntu/compro_2388010037/* /var/www/html/

            echo "=== FIX PERMISSION ==="
            sudo chown -R www-data:www-data /var/www/html

            echo "=== RESTART NGINX ==="
            sudo systemctl restart nginx

            echo "=== DEPLOY SUCCESS ==="